
classdef NeuroDataFloat < ros.Message
    %NeuroDataFloat MATLAB implementation of rosneuro_msgs/NeuroDataFloat
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rosneuro_msgs/NeuroDataFloat' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '32be46802288cbb30589c65e16703676' % The MD5 Checksum of the message definition
        PropertyList = { 'Info' 'Data' } % List of non-constant message properties
        ROSPropertyList = { 'info' 'data' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.rosneuro_msgs.NeuroDataInfo' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Info
        Data
    end
    methods
        function set.Info(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.rosneuro_msgs.NeuroDataInfo'};
            validateattributes(val, validClasses, validAttributes, 'NeuroDataFloat', 'Info')
            obj.Info = val;
        end
        function set.Data(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'NeuroDataFloat', 'Data');
            obj.Data = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rosneuro_msgs.NeuroDataFloat.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rosneuro_msgs.NeuroDataFloat;
            obj.reload(strObj);
        end
    end
end
